apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  profile: remote
  values:
    global:
      istioNamespace: external-istiod
      configCluster: true
    pilot:
      configMap: true
    istiodRemote:
      injectionURL: https://a3f7de7e3770542b59a995c9fd890d86-528898542.us-east-1.elb.amazonaws.com:15017/inject/cluster/cluster1/net/network1
    base:
      validationURL: https://a3f7de7e3770542b59a995c9fd890d86-528898542.us-east-1.elb.amazonaws.com:15017/validate