---
apiVersion: v1
kind: Service
metadata:
  name: carts
 
  labels:
    name: carts
  namespace: toy-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 7001
  selector:
    name: carts
