version: '2'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - ./alert.rules:/etc/prometheus/alert.rules
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        expose:
          - 9090
        ports:
          - 9090:9090
        links:
          - alertmanager:alertmanager
    nodeexporter:
        image: quay.io/prometheus/node-exporter:v1.1.2
        container_name: nodeexporter
        volumes:
          - '/:/host:ro,rslave'
        pid: host
        command:
          - '--path.rootfs=/host'
        restart: unless-stopped
        ports:
          - 9100:9100
    alertmanager:
        image: prom/alertmanager
        ports:
          - 9093:9093
        volumes:
          - ./alertmanager.yml:/etc/alertmanager/config.yml
        command:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
    grafana:
        image: grafana/grafana
        depends_on:
          - prometheus
        ports:
          - 3000:3000
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=foobar
          - GF_USERS_ALLOW_SIGN_UP=false
        links:
          - prometheus:prometheus
    importer:
      image: giantswarm/tiny-tools
      depends_on:
        - grafana
      entrypoint: /bin/sh import.sh
      working_dir: /opt/grafana-import-dashboards
      volumes:
        - ./grafana:/opt/grafana-import-dashboards
      links:
        - grafana:grafana
