apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: ""
        version: "v1"
        kind: "Pod"
      - group: ""
        version: "v1"
        kind: "Service"
      - group: "networking.istio.io"
        version: "v1alpha3"
        kind: "Gateway"
      - group: "networking.istio.io"
        version: "v1alpha3"
        kind: "VirtualService"
      - group: "networking.istio.io"
        version: "v1alpha3"
        kind: "DestinationRule"
      - group: "authentication.istio.io"
        version: "v1alpha1"
        kind: "Policy"
      - group: "rbac.istio.io"
        version: "v1alpha1"
        kind: "ServiceRoleBinding"